// Pure data factory for tests. Application entrypoints import server/packages.ts.
import official from './official.json' with { type: 'json' };
import {
  EvaluationPackageSchema,
  type Criterion,
  type EvaluationPackage,
} from '../schema';
const document = official.source.title;
const version = official.source.version;
const source = (page: number, quote: string) => ({
  document,
  version,
  page,
  quote,
});
function criterion(
  id: string,
  title: string,
  page: number,
  quote: string,
  expectation: string,
  question: string,
  action: string,
  priority: number,
): Criterion {
  return {
    id,
    title,
    source: source(page, quote),
    expectation,
    question,
    action,
    priority,
  };
}
const actual = {
  university: '성신여자대학교',
  track: '인문계열',
  year: 2026,
  kind: 'actual',
  minLength: 800,
  maxLength: 1000,
  requiredWords: [],
  paragraphCount: null,
};
const mock = { ...actual, year: 2027, kind: 'mock' };
export const packages: EvaluationPackage[] = [
  {
    ...actual,
    id: 'sungshin-2026-1-1',
    label: '2026 기출 · 1교시 문제 1',
    question: official.questions[0],
    source: source(37, official.questions[0]),
    requiredPassages: ['가', '나', '다'],
    tasks: ['국민연금의 역할 설명', '운용 방식 비교', '지속 운영 방안 논증'],
    concepts: [
      { label: '인구구조 변화', aliases: ['저출산', '고령', '노령'] },
      { label: '국민연금의 역할', aliases: ['국민연금', '노후', '재분배'] },
      { label: '운용 방식', aliases: ['부과', '적립', '싱가포르'] },
    ],
    criteria: [
      criterion(
        'a1-role',
        '인구 변화와 국민연금의 역할',
        46,
        '저출산·초고령사회 현상으로부터 나타나는 문제점을 이해하고 설명한다.',
        '저출산·초고령사회의 문제와 이에 대응하는 국민연금의 역할을 연결하는 설명',
        '제시문 <가>의 변화가 어떤 문제를 낳으며, 설명한 연금의 역할은 그 문제에 어떻게 대응하나요?',
        '인구 변화를 설명한 부분에서 문제와 국민연금의 역할 사이의 연결을 점검하고 필요한 논거를 보완하세요.',
        1,
      ),
      criterion(
        'a1-method',
        '두 공적연금 운용 방식의 이해',
        46,
        '제시문 <나>와 제시문 <다>에서 설명하는 공적연금의 운용 방식을 각각 이해하고 설명한다.',
        '국민연금의 특징·한계와 싱가포르 중앙적립기금의 운용 방식 차이에 관한 설명',
        '<나>와 <다>에서 보험료를 내는 사람과 급여를 받는 사람의 관계는 어떻게 다른가요?',
        '두 운용 방식을 다룬 부분에서 비교 기준을 맞추고 그 차이가 갖는 의미를 설명하세요.',
        3,
      ),
      criterion(
        'a1-proposal',
        '연금의 역할과 일관된 운영 방안',
        46,
        '작성자의 논지를 명확하게 서술하며 그에 대한 논거도 적절히 제시한다.',
        '앞서 설명한 연금의 역할과 모순되지 않는 운영 방안 및 그 논거',
        '제안한 방안은 앞서 설명한 연금의 역할을 어떻게 유지하거나 설명 가능한 방식으로 바꾸나요?',
        '운영 방안을 제시한 부분과 앞부분의 연금 역할 설명을 대조하고, 두 주장을 연결하는 논거를 보완하세요.',
        2,
      ),
    ],
    exceptions: [
      '공식 해설 43쪽: 논거가 명확하면 다양한 운영 방안이 가능하다. 완전적립방식만 정답으로 강요하지 않는다.',
      '해설 43쪽: 재분배를 연금의 역할로 제시하고 적립방식을 주장할 경우 두 내용을 잇는 논증이 필요하다.',
    ],
  },
  {
    ...actual,
    id: 'sungshin-2026-1-2',
    label: '2026 기출 · 1교시 문제 2',
    question: official.questions[1],
    source: source(37, official.questions[1]),
    requiredPassages: ['가', '나', '라', '마'],
    tasks: ['롤스·노직의 관점으로 판결 평가', '국민연금의 정당성과 한계 논증'],
    concepts: [
      { label: '롤스의 관점', aliases: ['롤스', '최소극대화', '최소 수혜'] },
      { label: '노직의 관점', aliases: ['노직', '자유지상', '소유권'] },
      { label: '정당성과 한계', aliases: ['정당', '한계', '불신', '고령'] },
    ],
    criteria: [
      criterion(
        'a2-view',
        '판결 이해와 두 정의관의 비교·평가',
        47,
        '제시문 <마>의 판결문을 롤스의 자유주의와 노직의 자유지상주의 관점에서 비교·분석하여 평가한다.',
        '청구인 주장과 재판부 결정의 파악 및 노직·롤스 관점과의 타당한 연계·비교 평가',
        '두 관점은 <마>의 어떤 주장이나 판단 이유와 연결되며, 그 연결의 이유가 답안에 드러나나요?',
        '판결을 평가한 부분에서 청구인과 재판부를 구분하고 각 철학과 연결한 논거를 확인하세요.',
        3,
      ),
      criterion(
        'a2-limits',
        '국민연금의 정당성과 한계',
        47,
        '제시문 <가>와 <나>에서 확인할 수 있는 저출산·고령화 현상으로 인하여 국민연금제도가 가지는 한계점을 논의한다.',
        '롤스 관점에서의 정당성·한계와 인구구조 변화에 따른 운영의 한계를 자료에 연결한 논증',
        '<가>·<나>·<라>를 근거로 연금의 정당성과 한계를 모두 설명했나요?',
        '국민연금을 평가한 부분에 정당성과 한계의 근거가 각각 있는지 확인하고 앞선 철학적 평가와 연결하세요.',
        1,
      ),
      criterion(
        'a2-coherence',
        '내용 정합성·용어·문장 연결',
        47,
        '논술 내용의 정합성, 단어 선택의 정확성 및 문장 간 연결의 논리성이 있는가?',
        '관점과 용어의 정확성, 앞뒤 판단의 정합성 및 문장 간 논리적 연결',
        '같은 용어를 같은 뜻으로 사용했으며 앞선 평가와 결론이 서로 일치하나요?',
        '인용한 부분과 앞뒤 문장의 용어·관점을 대조하고 생략된 논리적 연결을 보완하세요.',
        4,
      ),
    ],
    exceptions: [
      '공식 해설 45쪽: 가입기간에 따른 역진성의 구체적 논의는 필수가 아니다. 누락으로 감점하지 않는다.',
      '공식 해설 45쪽: 조세법률주의는 소득분배이론과 관련이 없으므로 억지로 대응시키지 않는다.',
    ],
  },
  {
    ...mock,
    id: 'sungshin-2027-mock-1',
    label: '2027 모의논술 · 문제 1',
    question: official.mock.questions[0],
    source: source(93, official.mock.questions[0]),
    requiredPassages: ['가', '나', '다'],
    tasks: ['세 관점 종합', 'AI 시대 교육의 필요성 설명'],
    concepts: [
      { label: '비판적 사고', aliases: ['비판', '사고', '주체'] },
      {
        label: '인간 자본과 경제',
        aliases: ['인간 자본', '인적 자본', '생산성', '경제'],
      },
      {
        label: '사회화와 공동체',
        aliases: ['사회화', '공동체', '규범', '사회 통합'],
      },
    ],
    criteria: [
      criterion(
        'm1-change',
        'AI 시대 교육의 변화와 도전',
        99,
        '학습자의 비판적 사고 능력에 대한 위협과 지식 생산의 주체에',
        'AI의 교육 기회 확대와 비판적 사고의 위협, 지식 생산 주체의 문제에 대한 이해',
        'AI의 정보 제공 능력이 커질 때 학습자의 사고와 판단에는 어떤 과제가 남나요?',
        '<가>를 다룬 부분에서 AI의 이점과 도전을 구분하고 교육의 필요성과 연결하세요.',
        1,
      ),
      criterion(
        'm1-capital',
        '인간 자본 이론과 교육의 경제적 의의',
        99,
        'AI 시대에도 교육의 경제적 의의가 유지되거나 강화된다는 점을 적절히',
        '인간 자본 이론을 활용해 AI 시대 교육의 경제적 의의가 유지되거나 강화되는 이유를 논증',
        '인간 자본 이론의 어떤 논거가 AI 시대에도 교육이 필요한 이유를 뒷받침하나요?',
        '<나>의 관점을 설명한 부분에 이론 소개와 자신의 결론을 잇는 논거를 보완하세요.',
        2,
      ),
      criterion(
        'm1-synthesis',
        '사회적 기능과 세 관점의 종합',
        99,
        'AI 시대에도 교육이 필수적인 이유라는 공통 질문으로 통합·종합하고 있는가?',
        '교육의 사회화·양면성 및 AI가 대체하기 어려운 사회적 기능을 파악하고 세 관점을 하나의 논지로 통합',
        '세 제시문은 교육의 필요성이라는 같은 질문에 어떻게 함께 답하나요?',
        '<다>를 설명한 부분과 결론을 확인하고, 세 관점의 관계를 드러내는 논증을 보완하세요.',
        3,
      ),
      criterion(
        'm1-expression',
        '어법·표현과 요구 분량',
        99,
        '정확한 어법과 표현을 사용하고 문제에서 요구하는 분량을 지켜서 논술하였는가?',
        '정확한 어법·표현과 800~1,000자 분량의 준수',
        '불명확한 지시어나 중복 표현 때문에 논거를 이해하기 어려운 곳은 없나요?',
        '내용 과제를 먼저 수정한 뒤 인용한 부분의 지시 대상·문장 호응을 확인하세요. 분량은 별도 규칙 검사도 참고하세요.',
        5,
      ),
    ],
    exceptions: [
      '해설 98·100쪽: 세 관점을 통합적으로 종합하면 강조점은 다양할 수 있다. 단순 나열과 통합의 사고 흐름을 구별한다.',
      '예시답안의 서술 순서나 표현을 필수로 요구하지 않는다.',
    ],
  },
  {
    ...mock,
    id: 'sungshin-2027-mock-2',
    label: '2027 모의논술 · 문제 2',
    question: official.mock.questions[1],
    source: source(93, official.mock.questions[1]),
    requiredPassages: ['다', '라'],
    tasks: ['AI 양면성 분석', '자신의 견해와 해결 방향 논증'],
    concepts: [
      {
        label: '문화 자본과 불평등 재생산',
        aliases: ['문화 자본', '디지털 자본', '재생산'],
      },
      { label: '기술 중립성 반론', aliases: ['중립', '사회 구조'] },
      {
        label: '접근 격차와 데이터 편향',
        aliases: ['문해력', '접근', '편향', '편견'],
      },
    ],
    criteria: [
      criterion(
        'm2-neutrality',
        '불평등 재생산과 기술 중립성 반론',
        99,
        '기술 중립성 반론의 타당성과 한계를 균형 있게 논증하고 있는가?',
        '문화 자본·불평등 재생산 관점을 AI에 적용하고 기술 중립성 반론의 타당성과 한계를 함께 검토',
        '기술 중립성 반론이 설명하는 부분과 설명하지 못하는 부분은 무엇인가요?',
        '<다>를 적용한 부분에 반론을 검토한 근거가 있는지 확인하고 자신의 평가와 연결하세요.',
        1,
      ),
      criterion(
        'm2-divide',
        '디지털 문해력 격차와 데이터 편향',
        99,
        '결과의 불평등을 동시에 발생시킨다는 점을 함께 서술하고 있는가?',
        '접근의 불평등과 결과의 불평등이라는 두 경로를 <라>에 근거해 구분하고 설명',
        'AI에 접근할 수 있는 조건의 차이와 AI가 내놓는 결과의 편향을 구분했나요?',
        '<라>를 분석한 부분에서 두 불평등의 발생 경로와 관련 근거를 각각 확인하세요.',
        1,
      ),
      criterion(
        'm2-position',
        '두 관점의 통합·자신의 견해·대안',
        99,
        '구체적이고 실현 가능한 대안',
        '교육 기회 확대와 불평등 심화의 양면성을 통합해 자신의 입장·의의·한계와 구체적 해결 방향을 논증',
        '두 관점을 종합한 나의 입장은 무엇이며, 제안한 대안은 분석한 문제에 어떻게 대응하나요?',
        '견해와 대안을 제시한 부분에서 앞선 양면성 분석을 근거로 사용하는지 점검하고 연결을 보완하세요.',
        2,
      ),
      criterion(
        'm2-expression',
        '어법·표현과 요구 분량',
        99,
        '정확한 어법과 표현을 사용하고 문제에서 요구하는 분량을 지켜서 논술하였는가?',
        '정확한 어법·표현과 800~1,000자 분량의 준수',
        '불명확한 용어나 문장 호응 때문에 내 입장이 흐려진 곳은 없나요?',
        '내용 과제를 먼저 수정한 뒤 인용한 부분의 용어와 문장 호응을 점검하세요. 분량은 별도 규칙 검사도 참고하세요.',
        5,
      ),
    ],
    exceptions: [
      '해설 98·101쪽: 특정 대안의 완결성보다 두 관점을 통합하여 자신의 견해를 정립한 사고 흐름을 우선한다. 예시답안의 대안만 정답으로 요구하지 않는다.',
    ],
  },
].map((p) => EvaluationPackageSchema.parse(p));
export function officialFor(pkg: EvaluationPackage) {
  return pkg.kind === 'mock' ? official.mock : official;
}
